### ISSUE TITLE
oneof fields support

### ISSUE THREAD

**Issue by randydom** [semin-alx/SAN_Protobuffer#3]
Please are [oneof fields](https://protobuf.dev/programming-guides/proto3/#oneof) supported ? : 
```
message SampleMessage {
  oneof test_oneof {
    string foo = 1;
    string bar = 2;
  }
}
```
If yes please can you tell how to <B>Serialize</B> and <b>Deserialize</b> that in Delphi .

Thank you

**Comment by semin-alx** [comment]
OneOf is not explicitly supported yet, but this problem is easily circumvented.
Your message can be represented as (see https://protobuf.dev/programming-guides/encoding/#oneofs)

```proto
message SampleMessage {
  string foo = 1;
  string bar = 2;
}
```

But with one restriction, you can only set the value for one field.
The example below will better explain my point:

```pascal
procedure SerializeSampleMessage(fooValue, barValue: string);
var
  SampleMessageType: TsanPBMessageType;
  SampleMessageObj: TsanPBMessage;
begin

   SampleMessageType:= TsanPBMessageType.Create(nil, 'SampleMessage');
   SampleMessageType.AddFieldDef(ftoOptional, ftString, nil, 'foo', 1);
   SampleMessageType.AddFieldDef(ftoOptional, ftString, nil, 'bar', 2);

   SampleMessageObj:= SampleMessageType.CreateInstance;

   try

     if (fooValue <> '') and (barValue <> '') then begin
       raise Exception.Create('Error: Only one field can have a value');
     end;

     if fooValue <> '' then begin
       SampleMessageObj.FieldByName('foo').AppendValueAsString(fooValue);
     end;

     if barValue <> '' then begin
       SampleMessageObj.FieldByName('bar').AppendValueAsString(barValue);
     end;

     SampleMessageObj.SaveToFile('test.bin');

   finally
     SampleMessageObj.Free;
     SampleMessageType.Free;
   end;

end;
```

**Comment by randydom** [comment]
> OneOf is not explicitly supported yet, but this problem is easily circumvented. Your message can be represented as (see [protobuf.dev/programming-guides/encoding#oneofs](https://protobuf.dev/programming-guides/encoding/#oneofs))
> 
> ```proto
> message SampleMessage {
>   string foo = 1;
>   string bar = 2;
> }
> ```
> 
> But with one restriction, you can only set the value for one field. The example below will better explain my point:
> 
> ```pascal
> procedure SerializeSampleMessage(fooValue, barValue: string);
> var
>   SampleMessageType: TsanPBMessageType;
>   SampleMessageObj: TsanPBMessage;
> begin
> 
>    SampleMessageType:= TsanPBMessageType.Create(nil, 'SampleMessage');
>    SampleMessageType.AddFieldDef(ftoOptional, ftString, nil, 'foo', 1);
>    SampleMessageType.AddFieldDef(ftoOptional, ftString, nil, 'bar', 2);
> 
>    SampleMessageObj:= SampleMessageType.CreateInstance;
> 
>    try
> 
>      if (fooValue <> '') and (barValue <> '') then begin
>        raise Exception.Create('Error: Only one field can have a value');
>      end;
> 
>      if fooValue <> '' then begin
>        SampleMessageObj.FieldByName('foo').AppendValueAsString(fooValue);
>      end;
> 
>      if barValue <> '' then begin
>        SampleMessageObj.FieldByName('bar').AppendValueAsString(barValue);
>      end;
> 
>      SampleMessageObj.SaveToFile('test.bin');
> 
>    finally
>      SampleMessageObj.Free;
>      SampleMessageType.Free;
>    end;
> 
> end;
> ```

Meaning :  <b>manual handling</b> !!

**Comment by semin-alx** [comment]
I'm working on it.

**Comment by randydom** [comment]
> I'm working on it.

Many thanks
